### ISSUE TITLE
Feeds directory

### ISSUE THREAD

**Issue by aisejohan** [pbelmans/gerby-website#100]
Should there be a `feeds` directory by default setup?

**Comment by pbelmans** [comment]
Do you mean, should this be standard functionality for any instance of Gerby? In that case, no. For Kerodon this doesn't make sense for instance (unless Jacob starts his own blog, or suddenly makes things open source, both unlikely events).

When customising things for Kerodon it will become clearer what is common, what is not, and how to separate the two better. Gerby is still in its experimental phase when it comes to being universally applied, for the Stacks project it should be more or less stable (we hope).

**Comment by aisejohan** [comment]
OK, thanks for explaining! Yes, I hope so too. Currently importing the latest history thing, just freshly created this morning...
