### ISSUE TITLE
Creating database

### ISSUE THREAD

**Issue by aisejohan** [pbelmans/gerby-website#102]
Why on line 41 in `gerby/tools/update.py` do we only loop over Tag, Proof, Slogan, History, Reference, Commit, Change and not also over Part, Dependency, Footnote, etc?

**Comment by pbelmans** [comment]
You mean at the end of the script? Line 41 is in the middle of the tag import method.

The (not very strictly applied) philosophy is that some tables are always dropped and recreated from scratch, whilst others are updated. In an ideal world the update script is better than what it is now, but compared to what we had before, the new script is much cleaner.

**Comment by aisejohan** [comment]
Yes at the end. OK, got it. Thanks.
