### ISSUE TITLE
contributors page does not function on test server

### ISSUE THREAD

**Issue by aisejohan** [pbelmans/gerby-website#103]
The error seems to be that the `app.resource_open` opens the file in ascii mode but it should be utf-8. Reading about this online, it seems this may be due to a python setting on the server and not a problem with the code. Here is part of the error output in server log:

`[wsgi:error] File "/var/www/html/stacks-gerby/gerby/views/stacks.py", line 61, in show_contributors`
`[wsgi:error]   for line in f:`
`[wsgi:error] File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode`
`[wsgi:error] return codecs.ascii_decode(input, self.errors)[0]`
`[wsgi:error] UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 226: ordinal not in range(128)`

The `app.resource_open()` just calls `open()` but it won't take an encoding...

**Comment by pbelmans** [comment]
This used to work when the code was located in my home directory, so this is weird. I'll try to look into this in the morning, but it might be a problem where I need either you or Peter to be awake for.

**Comment by pbelmans** [comment]
No idea why it broke now, but it's fixed.
