### ISSUE TITLE
Daniel's issues

### ISSUE THREAD

**Issue by aisejohan** [pbelmans/gerby-website#105]
The following suggestions are made by a user, let's call them Daniel, looking at the site on a phone.

- Hard to advance to next section: you need to click twice.
- Table of contents header too long: meaning that if you are at an equation for example, then the header breadcrumb thing takes up a lot of space. On the other hand, the user did think that the header provided useful information.
- Next button should always be available: when there is currently no `next` button, there should be an `up` button which jumps the browser up to the location of the current item. Example: if you are viewing a lemma and it is the last lemma of the section, the up button is a link to the target for the lemma in the section it is in. Alternative: find the end of the proof of the lemma in the section and go there. However, another user felt that this would not work if there was no subsequent text or latex environments in the section (also presumably this would be harder to code).

Personally, I like the `up` button suggestion. I feel the analogues thing for the first lemma in a section would be less useful (and indeed it wasn't suggested by the user) because you can just go up the breadcrumb.

**Comment by pbelmans** [comment]
* I couldn't design a non-cluttered interface where those appear outside breadcrumb. Also, breadcrumb is always available, the suggested links only at top ot bottom.
* I agree it can take up lots of space, but it's the only visible thing, and see next.
* The breadcrumb does exactly this, and is always visible. There's no clear alternative with different functionality in my opinion.

**Comment by aisejohan** [comment]
About the last point: when you click on the section in the breadcrumb you go to the *beginning* of the section.

**Comment by pbelmans** [comment]
Sorry, I didn't read things properly. Phrased like that it makes sense (even more so for Kerodon than the Stacks project I think). I'll have a go at implementing this.

**Comment by pbelmans** [comment]
One silly thing that I can't fix right now is the offset for the link caused by the always visible header. That would require fiddling with plasTeX output and styling, which I don't want to do this close to the release (not that it would be hard, but there might be ramifications).

**Comment by pbelmans** [comment]
And in any case, we need to improve the handling of the header offset at some point, to deal with variable size headers.

**Comment by pbelmans** [comment]
Can you update the server? I've implemented this now, then you can check whether you like it.

I discovered that we more generally deal with the sticky sidebar in a wrong way (but it only happens in sidecases). We need to think about that more carefully at some point.

**Comment by aisejohan** [comment]
OK, I tried this, but I think it is currently not an improvement. I'm worried about making too many changes close to the deadline, so I suggest we (for now) revert this and we get back to it later.

More detail: the "go to section button" IMHO shouldn't be there and it looks bad. Daniel's idea was to only change the thing in the sense that for the last lemma in the section, in stead of not having the next button, you have an up button in the location where you would have had the next button if it weren't the last lemma.

**Comment by pbelmans** [comment]
But that wouldn't make much sense, you always want to be able to jump into the surrounding context, not just if you happened to be at the last lemma.

I've put the extra output in comments.

**Comment by aisejohan** [comment]
Ok, well, if it doesn't make sense, then we don't do it.

One possible future fix: put a small up button *in between* previous and next?

**Comment by pbelmans** [comment]
Always, or only for things which are at the end of a section? If anything, it should be always, and then I think the solution I first implemented is better than putting it in the middle.

**Comment by aisejohan** [comment]
Agree to disagree?

**Comment by pbelmans** [comment]
Sure. We should revisit this in a few weeks, when the dust on the new website has settled.
