### ISSUE TITLE
Autocorrect

### ISSUE THREAD

**Issue by aisejohan** [pbelmans/gerby-website#107]
Currently it is impossible to leave a comment on the test site on my Android phone bc of the interaction between the spell checker + word suggestion of my phone and the editor. It's hard to describe but completely obvious when you try it. Doesn't happen here on GitHub for example... Maybe we can turn off some editor features when the site is in phone mode? Don't have an iPhone to test, but will ask others later today...

**Comment by pbelmans** [comment]
You're talking about the editor, not the name and email fields, right? I can just add `autocomplete="off"`, as per [MDN](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion), if you think that is what causes the problem.

**Comment by pbelmans** [comment]
Although, that's not how the editor works I'm afraid, as all kinds of CodeMirror shenanigans happens.

**Comment by aisejohan** [comment]
OK, you second comment confused me, but I think trying to set autocomplete off would be an idea to try. Yes, I am talking about the editor.

**Comment by pbelmans** [comment]
Could you test this with @chngr? Not having a smartphone makes it kind of hard to fix this, and I'm afraid that `autocomplete="off"` on the textarea won't change anything, as the actual editing happens somewhere else with the Markdown editor that we use.

**Comment by aisejohan** [comment]
OK, will try later today. Not a high priority since with the current website commenting on a phone is near impossible too (but it doesn't suffer from the same problem).

**Comment by chngr** [comment]
I just tried leaving a comment and it was fine, albeit no autocorrect of any kind was present; that is, neither did the site's comment box nor my phone's autocorrect nag at me when I, scandalously, tried to spell "colour" with no "u" (though I think only my phone would complain at me then), etc.

So I don't understand @aisejohan's complaint, though maybe because I am late to the party, this is because the autocomplete flag was already set off?

**Comment by aisejohan** [comment]
@chngr Maybe you could look at my phone later today? Let me know when you are in?

**Comment by pbelmans** [comment]
I haven't fixed anything, my job was to get you two physically together in order to figure out what is going on with Johan's phone.

**Comment by aisejohan** [comment]
Unfortunately, that fix didn't work. Namely, I noticed that the toolbar was gone! So although my phone could leave a comment, nobody else can use it. Commit 4d70641 fixes that, but that's where the strangeness starts. The icons are in reverse order and the separators are all pushed to the left. My feeling is that this is a problem with the css but I don't have the knowledge needed to fix it. You can see the problem on the test server.

I leave it up to you guys, but it may be the best thing to do is to revert  ed5c52f and 4d70641

**Comment by chngr** [comment]
Looks like the difference is this new fork already implemented internally a fix for weird button issues from before. Anyways, this is resolved in 31a7a0e by removing what looks like an old hack to make simpleMDE sane before.

**Comment by aisejohan** [comment]
Tested on firefox, chrome and chrome on android phone (very hard to clear cache... no hard refresh seems to be available for chrome on android phones). Fantastic!
