### ISSUE TITLE
Searching for etale doesn't work

### ISSUE THREAD

**Issue by aisejohan** [pbelmans/gerby-website#109]
Search for etale in the search box. You get 8 results. There should be hundreds. According to the current website 2094 results (from statements).

**Comment by aisejohan** [comment]
Sorry, 8 isn't what I get now. Now I get 248. Argh, it has to do with whether you pin it to look only for statements or not... but in any case it is too low a number I think.

**Comment by chngr** [comment]
See also my comments in #59. Incidentally, you will get 2560 results if you search for étale (with the accent!).

**Comment by aisejohan** [comment]
Argh, yes, but I didn't realize it at the time... May I add this to the spelling list in the file `gerby/views/search.py`? Please? Or is this going to cause trouble having utf-8 (or whatever encoding you'd have to use) in the code?

**Comment by chngr** [comment]
Since you asked nicely: sure! However, note that when you query "étale", it would not pick up anything spelt "etale". Luckily, I don't think that is a problem in this case, and that the only instances of "etale" should be in labels.
