### ISSUE TITLE
Telling search how many results you want isn't preserved in next search

### ISSUE THREAD

**Issue by aisejohan** [pbelmans/gerby-website#110]
Not a very important feature, but there it is.

**Comment by aisejohan** [comment]
This has to do with which search box you use...

**Comment by pbelmans** [comment]
The fields are synchronised, but the submit isn't, so if you enter inside the quicksearch you are submitting a different form.

**Comment by aisejohan** [comment]
Another thing is that if you collapse all the search results, then expand a specific chapter, expand a specific section, then click on a lemma link there, and then afterwards go back to the search results (using back button on browser), you get back to the search results expanded... Personally, I don't like this, but I even don't know if this is something that you could change.

**Comment by pbelmans** [comment]
We can save this rather easily actually. Some weirdness might happen if you search for results on one day, collapse / expand certain things, and then you do exactly the same search a few days later when there are new tags in the search output. But that's not something to worry about too much I'd say.

**Comment by aisejohan** [comment]
For me this is still an issue: searching in the search bar at the top always throws me back to listing only ten results + it forgets whether or not I want to search all tags or only statements. I almost would prefer just a button sending me to the "official" search function so it is the same everytime I search. On the other hand, it might be the right thing for most people, so maybe this was by design?

What happens with my user experience is this: when I am on the page of a tag I sort of have to use the search bar at the top because there is no direct link to the search page available. Could we make the magnification glass a link to the search page (without submitting the search form so we don't clear the settings in the cookie or whatever it is)?

**Comment by pbelmans** [comment]
The current behavior is "by design" insofar that I haven't implemented the extra things to get it working like you want. So,

1. I'll implement a permanent storage for the pagination / search options
2. I'll try to store the expansion data

**Comment by aisejohan** [comment]
Just want to reiterate that this is still happening. Let me explain the behaviour that for me personally would be the most convenient, but I understand if this is not possible, etc.

(1) Suppose I do a search and then I click &infin; and then I click collapse all and then I expand a part and then I click on a tag I want to see and then finally I hit the back button. Then I want the page to look exactly the same as when I left to go see the tag.

(2) If I do a search and I click on &infin; and then later I do another search (with either search box) then I would like to get all the result on the page. In other words, I want the number of results returned to be the same with either search box.

(3) If (2) is impossible, then I want the next best thing: currently, when you choose &infin; in the main search box and then do a search in the search box on the upper left corner, then it resets the cookie for the main search box. And vice versa. So I would like these to not be reset by the other form IYSWIM.

**Comment by pbelmans** [comment]
Good point, and I should kick November 2018 me for not doing this. I will take a look in the weekend (insofar that notion has any meaning left to it).
