### ISSUE TITLE
The QED \square isn't placed properly

### ISSUE THREAD

**Issue by pbelmans** [pbelmans/gerby-website#12]
See e.g. tag 02M4, or 0BEL, and probably many many others. Should be easy to fix, it's pure CSS.

**Comment by chngr** [comment]
This is resolved by commit d1b36a4 together with commit [``35d00d9``](https://github.com/pbelmans/plastex/pull/33/commits/35d00d9cdc262d37ec90e584c6c9a31dbef56d9c) on the plastex repository.
