### ISSUE TITLE
Switching between tags and numbers

### ISSUE THREAD

**Issue by aisejohan** [pbelmans/gerby-website#124]
When I leave a comment on the website then my browser switches from displaying the numbers to displaying the tags. This is a tiny bit annoying for me when I go through the comments because I prefer using the numbers (because of my work flow). Low priority to be sure.

**Comment by pbelmans** [comment]
That behaviour is intentional, to get more people to use tags in comments. I can turn it off if you don't like it.

**Comment by aisejohan** [comment]
Ah yes, I forgot about this. Let's leave as is for now.
