### ISSUE TITLE
Show number in the title, if numbers are enabled instead of tags.

### ISSUE THREAD

**Issue by redtrumpet** [pbelmans/gerby-website#126]
When trying to learn a new subject, it often happens to me that I have ~5+ tabs of the stacks-project open. I think it would be more convenient if the title would contain the numbers of the section/tag I'm visiting, instead of the tag id. Ideally the tag would be showed if tags are enabled, the number if numbers are enabled.

Maybe even show the title of the tag?

![guessing game](https://user-images.githubusercontent.com/640808/43843961-f5d2d2f2-9b28-11e8-803c-446e556b33cb.png)

**Comment by pbelmans** [comment]
Having a human-readable number in there would be a good idea, yes.

I thought about using the title, if available, but the problem is that those titles can contain mathematical symbols. Maybe I should try to get it working nevertheless.

I'll see what I can do.

**Comment by iblech** [comment]
(Relevant discussion also over at #123.)

**Comment by pbelmans** [comment]
Let's keep the discussion here, for no particular reason.

You are right @iblech, for the Stacks project there are only accents it seems, and the nice thing is that we already have parsed accents in the database, so no need to still parse them. I'll implement the suggested feature later this week.

For other projects (such as Kerodon, which is what I had in mind when I raised my objections) there can be mathematics in titles, and that wouldn't work so easily.

**Comment by pbelmans** [comment]
On closer inspection tag 05IR provides a problem. But it also provides a (fixable) problem for the breadcrumb. I guess I'll just not display the title if it contains something which looks like HTML.
