### ISSUE TITLE
Hello world

### ISSUE THREAD

**Issue by jcommelin** [pbelmans/gerby-website#132]
At the moment it is quite hard to get a new gerby project up and running. In fact, I did not succeed at all. It seems that some of the required scripts are still in the stacs-project's `scripts/` directory. How hard would it be to have a `gerby init` that will populate a (empty?) directory with the necessary directories and scripts? Ideally it would be possible to do:

    mkdir dummy
    cd dummy
    gerby test    -- check if all dependencies are there (plastex, pybtex?, jinja2)
    gerby init    -- set up the directory (tell the user in which directory to put .tex files)
    gerby web     -- create all the html files
    gerby run     -- run a local webserver (give user a link to localhost:5000 etc)

If the user doesn't do anything, this would give them a website with one "Hello world" section/tag and some Lorem Ipsum text.

-------

An alternative would be to have a repo inside `gerby-project` that is called `hello-world`. By cloning it, the user should have a populated directory. Afterwards, all that is needed should be running one `plastex` command, and then a local webserver.

**Comment by pbelmans** [comment]
This is now done in fact.
