### ISSUE TITLE
update script doesn't remove proofs when they no longer exist

### ISSUE THREAD

**Issue by aisejohan** [pbelmans/gerby-website#133]
When you change a lemma into a remark, then the proof doesn't get removed from the database somehow. Example is currently [here](https://stacks.math.columbia.edu/tag/0DDQ). I will fix this soon on the live server by starting with an empty database... (now done, so now you can't see the conundrum anymore...)

**Comment by pbelmans** [comment]
Okay, this should be an easy fix. Will do this, thanks!

**Comment by pbelmans** [comment]
There is an untested fix now.

**Comment by pbelmans** [comment]
I tested it, and the database is created accordingly.
