### ISSUE TITLE
Code printed at the bottom of the pages when comments are closed

### ISSUE THREAD

**Issue by aisejohan** [pbelmans/gerby-website#134]
See [this page](https://stacks.math.columbia.edu/tag/06UP) and scroll to the bottom. This has to do with commit 64a256c0944881d4bbd310260325406b96a97251

**Comment by aisejohan** [comment]
Sorry, I removed the stanza added in the commit mentioned above on the live server because it was too annoying as I was going through the comments because it also seemed to have the effect of forgetting my name and email and website... Not sure why...

**Comment by pbelmans** [comment]
Sorry, I don't quite get what was the problem. With "comments are closed" you mean collapsed? What exactly happened?

**Comment by aisejohan** [comment]
Yes, when the comments are collapsed on the webpage the actual php/html code from commit 64a256 was printed in plain text at the bottom of the page + the thing about it not remembering name, email, and website stuff.

**Comment by pbelmans** [comment]
I can reproduce it now, I'll fix it. Thanks!
