### ISSUE TITLE
Ugly bar under displayed equation in firefox

### ISSUE THREAD

**Issue by aisejohan** [pbelmans/gerby-website#135]
There is an ugly scroll bar on [Tag 0A9A](https://stacks.math.columbia.edu/tag/0A9A) in the displayed equation on my firefox `Firefox Quantum, 63.0 (64-bit)`. This is related to issie #63.

**Comment by pbelmans** [comment]
I changed the scrolling behavior for equations, hopefully without breaking something else.

**Comment by pbelmans** [comment]
Nope, this is not quite good enough. It turns out that the behavior was changed in Firefox 63, so it was working fine before. Testing a bit more for now.

**Comment by pbelmans** [comment]
Hmpf. Firefox is being rather annoying regarding this problem...

@chngr Any ideas? Am I missing something obvious?

**Comment by chngr** [comment]
I am having a lot of trouble recreating this. This issue does not seem to appear on any of the browsers I usually use (Firefox 64.0b12, Chrome 70.0..., Safari 12.0.1) nor on the release of Firefox 63.0 that I could find---it seems to be patched up to 63.0.3.

**Comment by pbelmans** [comment]
What is your value of `layout.css.overflow.moz-scrollbars.enabled` in `about:config`? Is it for some reason set to true?

**Comment by aisejohan** [comment]
Still there today on ubuntu with `63.0.3 (64-bit)` on `Ubuntu 18.10`.

**Comment by chngr** [comment]
@pbelmans: Nope, `layout.css.overflow.moz-scrollbars.enabled` is `false`.

So the scrollbar does appear when I make my browser window quite thin, though this behaviour is true across browsers. At least on my Firefox window, I measure that there is not scrollbar when the content frame is at `640px` or the `div.equation` is at `633px`, but anything smaller, even when the box more than big enough for the `223px` diagram`, will make the scrollbar appear.

**Comment by aisejohan** [comment]
This seems to have worked here! Thanks. Closing.
