### ISSUE TITLE
Google search results show list of tex commands

### ISSUE THREAD

**Issue by alexjbest** [pbelmans/gerby-website#137]
If I do a google search for  stacks project <https://www.google.com/search?q=stacks+project> I see:

Index—The Stacks project
https://stacks.math.columbia.edu/
\begin{equation*} \DeclareMathOperator\Coim{Coim} \DeclareMathOperator\Coker{Coker} \DeclareMathOperator\Ext{Ext} \DeclareMathOperator\Hom{Hom} ...

as the first result which contains tex macros rather than anything describing the stacks project.

 - This sort of thing could be controlled by using specific google comment tags to control *snippets* <https://support.google.com/gsa/answer/6329153#57a1e30a-63b2-4470-86a5-94a6c06912be> which should be simple to do
- or by rearranging the location of the hidden div with all the macros in to be after some content.
- Maybe adding a meta description tag <https://neilpatel.com/blog/meta-description-magic/> would be a non-google specific and generally useful thing to do.

Probably there are other solutions, or maybe nobody is too worried about this.

**Comment by pbelmans** [comment]
Ah, Google got confused _again_. At some point I noticed this, and then it seemed to have gone away so I didn't look into it further, or maybe I'm just mixing up things and it was broken all the time.

In any case, we only needed those macros for legacy comments using them. So I moved the definition to a different location (just before the comment section on each page), where it shouldn't appear in the results.

I have also added a `<meta>`.


Thanks!
