### ISSUE TITLE
Missing tag in listing of results using a tag

### ISSUE THREAD

**Issue by aisejohan** [pbelmans/gerby-website#143]
Tag [08ND](https://stacks.math.columbia.edu/tag/08ND) is used in the proof of Tag [08PT](https://stacks.math.columbia.edu/tag/08PT) but is not listed [here](https://stacks.math.columbia.edu/tag/08ND/statistics#dependencies). This is probably due to the fact that 08PT has two proofs.

**Comment by pbelmans** [comment]
I am confused. To me it seems it is listed *twice*, rather than never? Still something that can be improved upon, but I'm not getting the issue as described.

**Comment by aisejohan** [comment]
Very sorry. Don't know what happened.
