### ISSUE TITLE
Overlapping letters in mathjax in chrome

### ISSUE THREAD

**Issue by aisejohan** [pbelmans/gerby-website#152]
This may not be a problem with gerby-website. Also it only happens with chrome not with firefox.

If it doesn't happen for others, then we can chalk it up to my setup or ubuntu.

A particularly bad example is the first displayed equation in the proof of  https://stacks.math.columbia.edu/tag/0FD5

About MathJax says `MathJax.js v2.7.0
TeX Input Jax v2.7.0
HTML-CSS Output Jax v2.7.0
mml Element Jax v2.7.0
MathEvents Extension v2.7.0
MathMenu Extension v2.7.0
MathZoom Extension v2.7.0
TeX/AMSmath Extension v2.7.0
TeX/AMSsymbols Extension v2.7.0
fp Extension v0.1
tex2jax Extension v2.7.0
xypic Extension v0.1
Chrome v87.0.4280.88`

And for my firefox it says `MathJax.js v2.7.0
TeX Input Jax v2.7.0
HTML-CSS Output Jax v2.7.0
mml Element Jax v2.7.0
MathEvents Extension v2.7.0
MathMenu Extension v2.7.0
MathZoom Extension v2.7.0
TeX/AMSmath Extension v2.7.0
TeX/AMSsymbols Extension v2.7.0
fp Extension v0.1
tex2jax Extension v2.7.0
xypic Extension v0.1
Firefox v83.0`

**Comment by pbelmans** [comment]
It looks good in my Chrome v87, and identical (to the naked eye) in my Firefox. Can you post a screenshot? In any case it's likely a MathJax-related issue, Gerby doesn't do much to the content of equations.

**Comment by aisejohan** [comment]
![Screenshot from 2020-12-17 13-50-34](https://user-images.githubusercontent.com/4593307/102530235-06872600-406f-11eb-861e-abdf12a88295.png)

**Comment by aisejohan** [comment]
But I am sure this is just my setup over here since you don't have this issue. Thanks for the quick reply!
