### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by pbelmans** [pbelmans/gerby-website#17]
We should do benchmarks, and see whether there are certain bottlenecks.

**Comment by pbelmans** [comment]
With [muatik/flask-profiler](https://github.com/muatik/flask-profiler) this is actually extremely easy. Some quick clicking around on my local copy shows that the following pages are heavy (>0.1 sec):

- bibliography (almost 0.5 sec, consistently...)
- the statistics page for a tag if there are multiple dependencies, e.g. for tag 0118
- the search (as to be expected)

Actual tag pages are fine, with a maximum of 0.1 sec in my not very systematic test.

**Comment by PatrickMassot** [comment]
I haven't been following what happened (although I do receive notifications). Are you using server-side or client-side mathjax in the end? Are there instructions somewhere to setup a test web site (or maybe even a public test site) to see how far you went up to now?

**Comment by pbelmans** [comment]
So far we are using client-side MathJax (so these timings are not how long it takes for the user to see a fully rendered page).

I was going to write instructions for setting up the site one of these days (the [preliminary instructions for plasTeX](http://pbelmans.ncag.info/blog/2017/08/27/introduction-gerby-plastex/) have been available for a while). Eventually these will become `README.markdown`'s of course.

**Comment by pbelmans** [comment]
We are running profiling on the server now, I'll make dedicated issues for those pages which are slow.
