### ISSUE TITLE
Make comments aware of macros

### ISSUE THREAD

**Issue by pbelmans** [pbelmans/gerby-website#28]
Or edit all comments using macros.

**Comment by chngr** [comment]
Do you have an example of this issue? I just tried things locally and it appears that I can define macros in comments. You just need to have the `\newcommand` macro within a math environment.

**Comment by pbelmans** [comment]
Sorry, I meant that people might want to use the macros the Stacks project (or something else) defines. But Johan and I discussed this, and this is really low on the priority list, to the extent that it shouldn't be on the list at all. We don't want people to rely on macros that they cannot easily see, and that might change in the future.

So I'll use my hammer and banish this from the issues list.
