### ISSUE TITLE
Pages for parts (in the Stacks project) contain junk

### ISSUE THREAD

**Issue by pbelmans** [pbelmans/gerby-website#32]
This is due to the table of contents at the end of each chapter. We just need a separate TeX creation script for the website.

**Comment by pbelmans** [comment]
Needs to be fixed in `stacks/stacks-project`, not here.

**Comment by aisejohan** [comment]
Right! If you pull from aisejohan/stacks-project and then checkout the branch web, then the Makefile has a target `web` that makes a book.tex without these tables of contents. Also `scritps/add_tags.py` will add the tags of the parts to the tags file. If you run this first, second do `make web` then you get a book.tex which can be munged by plastex and gerby-website without problems (tested).

**Comment by pbelmans** [comment]
Great, thanks!
