### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by pbelmans** [pbelmans/gerby-website#35]
We would like to have a **line count** for the Stacks project, but given that Gerby never sees the LaTeX code we don't have that straight away now. We could sum up the number of HTML lines, but that feels like a crude approximation.

We also need a **page count**. Again, not easily accessible from Gerby right now.

**Comment by chngr** [comment]
Line counts are accessible after commit [eae2c93](https://github.com/pbelmans/plastex/commit/eae2c937ad18b12127553ec22ce46a43344e4be7) in the plasTeX repository. In particular, Gerby now outputs a `meta.statistics` file, which is a JSON object that contains the line count in the property `lines`.

**Comment by pbelmans** [comment]
For the page count we can use https://stackoverflow.com/a/17931249/348350.

**Comment by chngr** [comment]
Great. I guess we just need to implement pdf’s before this will happen.

**Comment by pbelmans** [comment]
They will not be implemented as a feature: they will just be assumed to exist in some location. I don't think there's an easy one-size-fits-all implementation available here.

**Comment by pbelmans** [comment]
Another thing that can go on the global statistics page: the number of lemmas, propositions, etc. It's just fun to see these things.

**Comment by chngr** [comment]
Yea, that should be easy. I will do that soon.

**Comment by pbelmans** [comment]
I'm working on some tag statistics now by the way.

**Comment by chngr** [comment]
Okay! Assume that I can output the number of each environment in the `meta.statistics` file if you wish.

**Comment by pbelmans** [comment]
There's no need for that, it's all in the database :).

**Comment by chngr** [comment]
Oh, good point! Nice! I guess you got this, then.

**Comment by chngr** [comment]
Page counts and line counts are now available, after commits a4af8e3d2debfb7e447caae8b336315cbfb402b9 and 95233bd61798bc58a235de26994b7f19fe438af8.
