### ISSUE TITLE
Search doesn't remember choice of number of results per page

### ISSUE THREAD

**Issue by aisejohan** [pbelmans/gerby-website#40]
This happens even if you change from "search all tags" to "search only statements".

Additionally, if you just searched using "search only statements" and then you click the `50` box, then it jumps back to "search all tags".

This is with commit 51b35623c4a138f8c449ea3cb4ccb1f61add75b4

**Comment by pbelmans** [comment]
Good catch, I didn't implement this. Will do. Thanks!

**Comment by pbelmans** [comment]
Fixed.

**Comment by pbelmans** [comment]
Clicking the search button removes the options though!
