### ISSUE TITLE
Separate database for comments

### ISSUE THREAD

**Issue by aisejohan** [pbelmans/gerby-website#43]
As the Stacks project maintainer, I think it makes sense to have one database for the mathematical content of the site and a separate one for the comments. Namely, everything in the database except for the comments is currently generated by scripts acting on the Stacks project. Splitting the database into two databases would mean that if we update the Stacks project we can run all the update scripts locally and then simply copy over the database to the live server without touching the comments database.

**Comment by pbelmans** [comment]
Oh, you made this into an issue, I didn't see that. It's done in any case :).
