### ISSUE TITLE
Give visual clue in treeview of when results have slogan, reference or history

### ISSUE THREAD

**Issue by pbelmans** [pbelmans/gerby-website#44]
I'm just looking for an excuse to use [Bootstrap's badges](https://getbootstrap.com/docs/4.0/components/badge/) probably.

**Comment by chngr** [comment]
Maybe add slogans, history, etc. as the alt-text to the badge?

**Comment by chngr** [comment]
The alt-text is implemented in commit 1808b32.

**Comment by pbelmans** [comment]
If we're doing Bootstrap-y things, we might just change the alt-text into https://getbootstrap.com/docs/4.0/components/popovers/, because we can :).

**Comment by pbelmans** [comment]
I've changed these to popovers now. There is still an issue with the z-index: if you open a popover and start scrolling the top bar goes beneath the popover, which doesn't make sense.

**Comment by pbelmans** [comment]
Also do this in the search results by the way.

**Comment by pbelmans** [comment]
Okay, everything is done it seems.

By the way, I changed back to putting them on the bottom, because on mobile devices there is not enough space on the left.
