### ISSUE TITLE
Extend list of spelling suggestions

### ISSUE THREAD

**Issue by pbelmans** [pbelmans/gerby-website#59]
I remember the following (short) list from the discussion after lunch:
* pseudo-coherent
* semi-continuous (or maybe that one *is* spelled without -?)

**Comment by pbelmans** [comment]
In 4978963 I've extended the list of search suggestions a little bit.

I'm mentioning @aisejohan and @chngr to ask them: do you have some others?

**Comment by chngr** [comment]
These are not strictly spelling suggestions, but rather a note that we should make search a bit fuzzier:
  - Searching `fiber` should give anything with `fibre`, and vice versa. (Unfortunately, both are used in the Stacks Project...)
  - How about plurals? For example, maybe searching `topos` should give things for `topoi`, and vice versa.
  - I am never sure how to spell the infinitive of "glue", nor is @aisejohan apparently. Looks like `glueing` and `gluing` should both be searched given one.
  - Words with accents are a nightmare. Search for `Kunneth` should include results for `Künneth`; `Kahler` should include results for `Kähler`. 
  - And then there is `étale`, though this appears to be problematic only when searched in quotations, as you must when searching for `pro-étale`; see, however, e5d8c09.
  - ...

**Comment by pbelmans** [comment]
I personally don't want it to be too fuzzy. Google is too fuzzy for me for instance, and so is the new arXiv search. That being said:

* spelling should be consistent, so `fiber` should become the default (the Stacks project is American English, right?), then `fibre` becomes a disambiguation
* this is for me (personally) on the borderline of too fuzzy, but we can consider it @aisejohan likes the idea
* it should be `gluing` apparently, but we can add the disambiguation then
* we should indeed add disambiguations for accented words: no need for fuzziness here in my opinion
* with the disambiguation for `pro-étale` there is no problem I think

One thing I realise now is that some people might want to write `\'etale`. Do we want to deal with that too? Parsing TeX accents opens a whole Pandora's box of problems though...

**Comment by aisejohan** [comment]
In order to future proof these kind of things, I think you need to allow both American and English spellings for all words to occur in the Stacks project simultaneously. It is impossible for a text this large to be consistent everywhere. Moreover, over time I hope to hand off parts of the Stacks project to others who will use their own spelling in those parts. Personally, I love to write "glueing" and my dictionary says that it is correct, so I don't think we need to change it.

**Comment by pbelmans** [comment]
I'll try to come up with a good solution. But I don't want to write a neural network that learns different spellings etc. Maybe we will just have to have both spellings as disambiguation to each other. Using both spellings simultaneously in queries is annoying implementation-wise it seems.

**Comment by chngr** [comment]
Here is a naïve solution: check if an ambiguous term is in a query, and then extend the query with an `OR` statement.

For instance, if `query = "fiber product"`, we would check internally that `"fiber" in query` and then replace `query` by `query = "{query} OR {query.replace("fiber", "fibre")}`. Of course, making this robust will be quite annoying...

**Comment by pbelmans** [comment]
No need to keep this open I guess.
