### ISSUE TITLE
Italic text versus width

### ISSUE THREAD

**Issue by pbelmans** [pbelmans/gerby-website#64]
Looking at tag 0200, you see (at least in Chrome, on a laptop) that the "may" is cut off in the middle of the `y`, and that it is possible to wiggle around an epsilon amount by scrolling the tag display. Neither should happen in this example.

@chngr mentioned this problem before, but I forgot about this. Sorry!

**Comment by pbelmans** [comment]
Adding some padding might do the trick according to some googling, will try later.

**Comment by chngr** [comment]
This is done in af3f046. At least all the text I see now is on the screen!
