### ISSUE TITLE
Server complains about missing BookStatistic

### ISSUE THREAD

**Issue by aisejohan** [pbelmans/gerby-website#68]
It should just display something if this happens

**Comment by pbelmans** [comment]
Yes. Or the update script should just insert 0 when it can't determine the number of pages or number of lines. Will fix this in one way or the other.

**Comment by aisejohan** [comment]
Actually, I want it to work even if I cannot get the update script to work or if by running the update script I have accidentally deleted that table of the database (which in my experience is always going to happen after running the same script correctly for several years; for example an accidental control-C during updating). I know you are having a vacation, so I am just putting some things here that are easy to fix, so we don't forget.

**Comment by chngr** [comment]
Done in 8879da3. Some further safety features are added in following commits.
