### ISSUE TITLE
Improve location of end proof symbol

### ISSUE THREAD

**Issue by aisejohan** [pbelmans/gerby-website#69]
Look at Section Tag 00DY at the placement of the end proof symbol of first lemma. This also happens on the current website. I am not sure how worth fixing this is because I am against adding more vertical space in general. (I can easily fix this in the latex for example.)

**Comment by chngr** [comment]
Commit 2fa166e is an example for how we could fix this, at least in the case of list items. I don't see an easy general way to fix all these issues. Personally, I think it's just good mathematical/LaTeX-ical style not to end proofs in lists, equations, etc. But I guess I am rather particular about my LaTeX...

**Comment by aisejohan** [comment]
Yeah, I think you are right this should just not happen. For this lemma somebody else wrote the proof if this lemma a looooooooong time ago so it isn't even my fault!
