### ISSUE TITLE
Less vertical space at the beginning of a list

### ISSUE THREAD

**Issue by aisejohan** [pbelmans/gerby-website#70]
If a list occurs in a paragraph which in the latex file means it looks like this
<pre><code>This is a
\begin{enumerate}
\item List,
\item continuing
\end{enumerate}
</code></pre>
then I think currently a combination of plastex and gerby-website puts too much space before the first list item (just as in the current server). I think Tag 00DY is a good example; if you don't think this is ugly, then don't fix this. My feeling is that in the pdf there is always a bit more vertical space between text and the beginning of an environment than inside an environment between different parts of the environment.

**Comment by chngr** [comment]
I don't think Tag 00DY is necessarily ugly at the moment, but the lessening of vertical space does make it prettier. A quick adjustment is done in 753c90f. Adjust it to your liking!

**Comment by aisejohan** [comment]
Amazing!
