### ISSUE TITLE
Flexibility in update.py

### ISSUE THREAD

**Issue by aisejohan** [pbelmans/gerby-website#71]
I would like to suggest that we find a mechanism for making it easier to skip certain parts of the update script `update.py`. For example, currently there are the parts

1. Importing tags
2. Importing proofs
3. Importing footnotes
4. Populating the search tables
5. Assigning chapters to parts
6. Checking inactivity
7. Creating dependency data
8. Importing history, slogans, etc.
9. Importing names of tags
10. Importing bibliography
11. Computing statistics

Note that before running number 8 I need to update the history in the database which is done by a script in stacks-tools, so it is actually somewhat necessary for me to be able to do this.

For example if each of these was made into a python function, then the file could call them 1 by 1 at the end and I could easily comment out the ones I don't want to do (for example the one about creating dependency data which is very slow).

Moreover, the standard form of the file could comment out the updates which depend on the Stacks project infrastructure, I believe these are numbers 8, 9 (?), 10 (?), 11. Correct? Or maybe these could go into their own extra update script as would be convenient for me?

Finally, I would like the setup to be such that if the website is working (somewhat) and then I run one of these updates, then the website keeps working (somewhat + epsilon). In other words, I would like the updates to keep working even if we are mixing revisions of the stacks-project. (I understand this might be too much to ask.)

**Comment by chngr** [comment]
I have begun work on this in commit cf57427. You can now toggle any of the steps involved. There is still work in making this interface more pleasant, and probably some refactoring in `update.py`. And, of course, there should be more robustness built into the website, accounting for when certain tables break, etc.

More later.

**Comment by pbelmans** [comment]
Would it make sense to have an option to first toggle everything off, and then selectively switch things on?
