### ISSUE TITLE
Less vertical space around equations

### ISSUE THREAD

**Issue by aisejohan** [pbelmans/gerby-website#72]
I'd like there to be less vertical space around displayed mathematics (but again it is possible I am the only mathematician in the world who thinks so). An example is Section Tag 002D. In that section in the remark 002H there is more space before than after the mathematics which may be a different issue.

**Comment by chngr** [comment]
This is dealt with through 98440d0 and [ea09c79](https://github.com/pbelmans/plastex/commit/ea09c7939bd691554c8e1495a7f52f1c30ac9bda) in the plasTeX repository.
