### ISSUE TITLE
Should we strip HTML for the search table?

### ISSUE THREAD

**Issue by pbelmans** [pbelmans/gerby-website#77]
Right now searching for span gives way too many results from a user's point of view. We could strip HTML from the text in the search table. Would this be a good idea?

**Comment by pbelmans** [comment]
Words that might be annoying are: `span`, `class`.

**Comment by chngr** [comment]
I think this would be fine. The only information that could potentially be lost seems to be the tag. But, presumably, tags can be found elsewhere.

For a quick solution, there is the the [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/) library. Or else there is a direct solution on [this](https://stackoverflow.com/questions/753052/strip-html-from-strings-in-python) StackOverflow question.

**Comment by pbelmans** [comment]
We'll do this when we get the first person complaining about this. Not adding it to the release milestone for now.

**Comment by pbelmans** [comment]
I actually implemented this in the Kerodon fork.
