### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by PatrickMassot** [pbelmans/gerby-website#82]
There have been some discussion about setting up Travis CI in #67. I ran a small experiment in my fork https://github.com/PatrickMassot/gerby-website

It means I asked for Travis acces using https://github.com/marketplace/travis-ci and then added https://github.com/PatrickMassot/gerby-website/blob/master/.travis.yml in my fork (no other change). 

After quite a bit of trial and error (waiting half an hour for each try...), the result is: https://travis-ci.org/PatrickMassot/gerby-website 

Now each time I push to my fork, some remote computer (virtual machine actually) follows the steps listed in my `.travis.yml` file to clone your plastex fork, stacks-project, gerby-website and create the database (without search and stats because I wanted to save time when figuring out the process). The green color you see means that every step was executed without error.

There are various ways this could be useful, both in the final developing stages that you are entering and in production. In production you can imagine that each push to the stacks projects triggers the full build *and* deploys to the live web site if there have been no error.

Currently it also serves to document the full build process. We have all seen that blog posts and Github issue discussions can't be kept up to date. With Travis you immediately see if some change to the code requires updating the build instructions, because the Travis build fails until you correctly update `.travsi.yml`. Also you can guarantee that these instructions do not secretly rely on some specific setup of your computer: Travis uses a fresh Ubuntu with python3.6 install. Of course one could add configuration for MacOS or Windows.

Something voluntarily silly: the build steps include cloning again the current repo (which is done at the very beginning by Travis). This is because I wanted to document the full build process, and also because you may want to move this to another repository (stacks-project probably).

**Comment by PatrickMassot** [comment]
Oh, I just saw https://github.com/PatrickMassot/gerby-website/commit/9bd297bfa62df84e800bf080114d80c1d53adc78#commitcomment-27808995 My surprised had been discovered :wink:

**Comment by pbelmans** [comment]
This is awesome! Thanks a lot for doing this. Feel free to make this a pull request, for the time being it would make sense to have this running for this repository.

Continuous deployment is also an interesting idea, not necessarily for the Stacks project I think (because of [stacks/stacks-history](https://github.com/stacks/stacks-history)) but it could be great for other (smaller) projects.

**Comment by PatrickMassot** [comment]
It's really up to you what you want to do with Travis. I only wanted to help you start experimenting with this. 

However there is a time limit of 50 minutes per job:
https://docs.travis-ci.com/user/customizing-the-build#Build-Timeouts
I hit the limit when trying to include search and stats. I'll PR the working one and let you play with this (maybe one can split the build in several jobs, I don't know).

**Comment by pbelmans** [comment]
You are right, it should indeed be possible to split the build into several jobs: on https://docs.travis-ci.com/user/customizing-the-build/#Build-Timeouts it says

> There is no timeout for a build; a build will run as long as all the jobs do as long as each job does not timeout.

We can also try to get the PDF build in its own separate job (in particular when we are actually running Travis on the Stacks project repository, not from within this repository). None of the different steps (pdflatex, plastex, update script) should take longer than 50 minutes.

**Comment by pbelmans** [comment]
No need to keep this open at this point. Thanks for the effort!
