### ISSUE TITLE
Have pdf's per part?

### ISSUE THREAD

**Issue by pbelmans** [pbelmans/gerby-website#85]
In the overall table of contents you can click on a part, which gives you the same information as you already had on the page you were on, but only for this part.

Giving the whole treeview on the part page might be too much for the server though. We should test and check whether this is the case.

**Comment by pbelmans** [comment]
Also, we don't have pdf's for parts. Might be useful.

**Comment by pbelmans** [comment]
We should go for the middle ground: give a list of chapters and sections on the part page, give sections en lemmas on the chapter page.

**Comment by pbelmans** [comment]
Getting @aisejohan involved in the discussion: he has to change the Stacks project Makefile for this after all.

**Comment by aisejohan** [comment]
OK with doing this in principle, but I am worried overall with the assumptions that go into this. Would this mean other people using gerby-website would have to do the same?

**Comment by pbelmans** [comment]
Those are the kinds of customisations that people who want to use Gerby will have to decide for themselves. It's just a matter of (not) having links on certain pages, Gerby is not responsible for the creation of the pdf's. It's not supposed to be perfect straight out of the box, because every project will be different.

Gerby is free, but *support* for Gerby isn't. It's how Raymond and I will become millionaires!

**Comment by aisejohan** [comment]
Likely story!

**Comment by pbelmans** [comment]
Quick reminder for @aisejohan, at the moment this is the only thing left to be done for the release.

The following would be convenient filenames, as they are based on the label in the TeX, so that everything is automated:

1. `preliminaries.pdf`
2. `schemes.pdf`
3. `topics-in-scheme-theory.pdf`
4. `algebraic-spaces.pdf`

etc.

**Comment by pbelmans** [comment]
These is actually a problem this way: there will be two files named `schemes.pdf`. So the file for part 2 should be called `part-schemes.pdf`, likewise for the others.

**Comment by aisejohan** [comment]
OK, so I am going to put `part-` in front of all of the names. But I am not sure where you are taking the names `preliminaries`, `schemes`, `topics-in-scheme-theory`, etc from? I guess you are taking these from the current website?

**Comment by pbelmans** [comment]
These are in the label, except that the tags for parts are not yet in the actual tags file. So that's another thing that needs to happen.

**Comment by pbelmans** [comment]
By, "in the label" I mean that at some point we created a modified tags file, containing tags for parts. These are the labels I am referring to. So

1. We need to permanently add tags for parts.
2. The labels associated to these tags are what should be used for the filename of the parts.

**Comment by aisejohan** [comment]
Yes, OK, so the only place we store these are going to be in the tags file. Currently I am making these tags and their names from the file `chapters.tex` in the script `add_tags.py` which uses the function `get_parts` to find the parts...

**Comment by pbelmans** [comment]
These must be in the tags file, as that is the philosophy of Gerby. So the fact that currently they are not in the tags makes it impossible to run plasTeX on the output of the `web` directive in the Makefile.

**Comment by aisejohan** [comment]
Right, yes, I am going to add them to the tags file soonish... I am first going to update the current website one last time...

**Comment by aisejohan** [comment]
OK, I was just looking at this. Of course, it is relatively easy to make parts latex files. But getting the references and the numbering to work out correctly is a huge pain in the neck. Currently, when you compile the book.tex (either the one that is created in `tmp` which has no tag information or the one created in `tags/tmp` which does have the tag info) then the internal refs work. Or if you compile all the chapter files into pdfs (either in the main directory of `stacks-project` or when running the `make tags` target) then the cross references work and more importantly you don't get `??` when there is a reference. In other words, when you have downloaded only one of the chapter pdfs, then of course the cross refs don't work, but at least you see the chapter name and `section.number` where you should look for the reference.

Of course it is *possbile* to get this working with parts also, but I don't want to invent a system where you get crossreferences between the parts pdfs and get a whole new numbering scheme which may confuse readers. Yes, I know I can also get the numbering to work out too, but it is just too cumbersome and not worth it in my opionion. In stead, may I suggest that in stead of the parts.pdf download you offer a list of chapter.pdf downloads in stead? Is this easy to do in the website code?

Let me know.

**Comment by pbelmans** [comment]
You are right that doing this is opening Pandora's box. So let's not do this for, I'm okay with that.

We could collate all the chapter pdf's (preferably in the Makefile), but that's a suboptimal solution.

In an ideal world the setup for all the TeX files is sufficiently flexible to handle parts too. But I'm not volunteering to rewrite all the Python and Makefile code to accomplish this :). So I'll remove the part links again for now.

**Comment by pbelmans** [comment]
Closing this for now.
