### ISSUE TITLE
Stripped URL in Text of 01FY

### ISSUE THREAD

**Issue by chngr** [pbelmans/gerby-website#92]
In the text of [01FY](https://stacks.math.columbia.edu/tag/01FY), in the second sentence of the final paragraph, there is a url that is directly embedded into [the text by a ``\url`` command](https://github.com/stacks/stacks-project/blob/6f7193f9960a16e4b9d3d69903d14f4868ec9b9e/hypercovering.tex#L65). The url text is completely missing in the corresponding page of the [test version](https://stacks-test.math.columbia.edu/tag/01FY).

(As a side note, the ``~`` is swallowed up by whatever parser in the former setting and the link does not work anyway.)

**Comment by pbelmans** [comment]
This is a plasTeX issue it seems, no? Namely pbelmans/plastex#49.

**Comment by pbelmans** [comment]
Fixed by plasTeX.
