### ISSUE TITLE
Tag 01V4 has a render issue

### ISSUE THREAD

**Issue by pbelmans** [pbelmans/gerby-website#95]
The equation has a special labeling or something.

**Comment by pbelmans** [comment]
This is caused because `data-marker` cannot deal with mathematics. I don't think there's any good solution to this in plasTeX or Gerby.

@aisejohan Are you okay with changing this in the TeX code for the Stacks project? Anything not involving $'s would be good.

**Comment by aisejohan** [comment]
OK, I changed this particular one, but there are about 28 others... Let me take a look at how bad it would be to change those.

**Comment by pbelmans** [comment]
You can use `*` without $'s around it.

**Comment by aisejohan** [comment]
Is it OK to have `\item[]` with plastex?

**Comment by chngr** [comment]
Yes. Though there are some improvements that I need to be making to it...

**Comment by aisejohan** [comment]
I mean with `[]` empty! In other words, nothing between the square brackets... Still OK?

**Comment by pbelmans** [comment]
Yes, should be fine I think. The problem is not plasTeX, it's the way we render things in HTML. There is no nice way of dealing with mathematics in list markers there. If `\item[]` is broken, then that is a plasTeX bug.

**Comment by aisejohan** [comment]
OK, done
