### ISSUE TITLE
recent-comments.xml

### ISSUE THREAD

**Issue by aisejohan** [pbelmans/gerby-website#98]
The `recent-comments.xml` page does not yet work correctly. What seems to be missing is in the `gerby/views/comments.py` one needs to add more information to the call of `render_templace`

**Comment by aisejohan** [comment]
Are you sure this fixes it? I think there needs to be a change in the file `gerby/views/comments.py` on line 20??? I'm going to reopen this until I can test the solution in about an hour or so.

**Comment by pbelmans** [comment]
Yes: the problem was that

* I used the wrong field for the author's name
* the database structure has changed: comments are now in a separate database, so there's no implicit JOIN happening on the tag field anymore

Locally it works fine, and I don't see any reason why it wouldn't on the server.

**Comment by aisejohan** [comment]
OK, sorry, yes this is fine now. My browser doesn't see the `xml` page as an xml page. So now I am testing it in my rss reader...

**Comment by aisejohan** [comment]
My feed reader complains about `LibXML error 63 at line 124 (column 7): CData section not finished <p>Yes, this seesm true!</p>]] ></content:encode`

**Comment by pbelmans** [comment]
That was a weird typo.

**Comment by aisejohan** [comment]
OK, will test...

**Comment by pbelmans** [comment]
I'm validating it through W3C now, fixing some issues.

**Comment by aisejohan** [comment]
While you're at it: my rss reader often complains about weird characters in the names of people for the current rss feed... Especially german characters it seems.... For example in the `https://stacks.math.columbia.edu/tag/03T4#comment-3293` the double s causes trouble. It could be my feeed reader of course...

**Comment by aisejohan** [comment]
I'm using tt-rss

**Comment by pbelmans** [comment]
Everything should be UTF-8 the way we serve it. In which way does it cause trouble?

**Comment by aisejohan** [comment]
Here is the error: `LibXML error 26 at line 97 (column 49): Entity 'szlig' not defined` I checked and this refers to the double s. But again this is for the current version not the new one.

**Comment by pbelmans** [comment]
Ah, that might be fixed now, because the new code will output UTF-8 there, no HTML encodings are used where they shouldn't.

**Comment by aisejohan** [comment]
Opening this again until it works on server. It may not be because of the code but still...

**Comment by aisejohan** [comment]
OK, and now it works...

**Comment by pbelmans** [comment]
The files on the server were outdated. I'll pingpong this again to a closed state.
