### ISSUE TITLE
Location of book.pdf in update.py

### ISSUE THREAD

**Issue by aisejohan** [pbelmans/gerby-website#99]
The script `update.py` looks in the wrong place for book.pdf IMHO. Namely, we do have a location where book.pdf resides, namely, it is in `download` which in the case of the Stacks project is in `tex/tags/tmp` so is already in the code. Maybe this should be a configuration variable too (to be used in both places)? I'd really prefer this over the current solution... but I could be wrong.

**Comment by pbelmans** [comment]
Yes, I realised that the page count was not working properly for the current setup. I'll come up with a nice solution for this.

**Comment by pbelmans** [comment]
The PDF is now part of the configuration. You can point it wherever you want.
